"""Add new table

Revision ID: 081f6c513b8b
Revises: 
Create Date: 2025-08-08 18:05:24.863618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081f6c513b8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('instrument', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('instrument', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('instrument', 'instrument_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument', 'instrument_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('instrument', 'updated_at')
    op.drop_column('instrument', 'created_at')
    op.drop_table('instrument_notes')
    # ### end Alembic commands ###
